name:                AblyPrelude
version:             0.1.0.0
github:              "githubuser/AblyPrelude"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AblyPrelude#readme>

dependencies:
- base >= 4.7 && < 5
- aeson-pretty
- lens
- time
- transformers
- pretty-simple
- containers
- text
- bytestring
- generic-lens
- deepseq
- safe-exceptions
- cereal
- unordered-containers
- dlist
- mtl
- reflection
- random
- MonadRandom
- foldl
- linear
- profunctors
- contravariant
- semigroupoids
- aeson
- vector
- terminal-size
- pipes
- cereal-text
- pretty-show
- directory
- blaze-html
- file-embed
- template-haskell

default-extensions:
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DeriveGeneric
- DerivingVia
- StandaloneDeriving
- GeneralizedNewtypeDeriving
- PolyKinds
- KindSignatures
- DataKinds
- LambdaCase
- BangPatterns
- BlockArguments
- RankNTypes
- ScopedTypeVariables
- GADTs
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- InstanceSigs
- TypeSynonymInstances
- ExplicitNamespaces
- PackageImports
- TypeFamilies
- TypeFamilyDependencies
- TypeApplications
- TypeOperators
- ViewPatterns
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

tests:
  AblyPrelude-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AblyPrelude
